# Generated by Django 5.1 on 2024-09-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productscrapeevent',
            old_name='products',
            new_name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, help_text='Scrape daily?'),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productscrapeevent',
            name='asin',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
