# Generated by Django 5.1 on 2024-09-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_productscrapeevent_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
        migrations.AddField(
            model_name='product',
            name='_trigger_scrape',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='trigger_scrape',
            field=models.BooleanField(default=False),
        ),
    ]
